#ifndef AOC2020_INCLUDES_H
#define AOC2020_INCLUDES_H
#include <iostream>
#include <fstream>
#include <cstdio>
#include <algorithm>
#include <iterator>
#include <string>
#include <vector>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <regex>
#include <reflex/matcher.h>
#include <reflex/boostmatcher.h>
#endif //AOC2020_INCLUDES_H
